ogit: Rewrite and reconfigure

diff --git a/bin/ogit b/bin/ogit
--- a/bin/ogit
+++ b/bin/ogit
@@ -1,272 +1,330 @@
-#!/usr/bin/env python3
+#!/bin/bash
 
-import configparser
-import glob
-import os
-import os.path as path
-import pwd
-import re
-import shlex
-import subprocess as subp
-import sys
+# Copyright 2014 Chad Versace
+# 
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+# 
+#     http://www.apache.org/licenses/LICENSE-2.0
+# 
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
-prog_name = None
-HOME = os.environ.get('HOME', pwd.getpwuid(os.getuid()).pw_dir)
-XDG_CONFIG_HOME = os.environ.get('XDG_CONFIG_HOME', path.join(HOME, '.config'))
-OGIT_CONFIG_HOME = path.join(XDG_CONFIG_HOME, 'ogit')
-OGIT_CONFIG_MAIN = path.join(OGIT_CONFIG_HOME, 'config')
-OGIT_REPOS_DIR = path.join(OGIT_CONFIG_HOME, 'repos')
+# TODO:
+# Fix bad gitlink issue.
 
-def die(msg):
-    sys.stderr.write('{0}: error: '.format(prog_name))
-    sys.stderr.write(msg)
-    sys.stderr.write('\n')
-    sys.exit(1)
+: ${ogit_debug:=0}
+if [[ "x$ogit_debug" != "x0" ]]; then
+    set -vx
+fi
 
-def check_git(args):
-    args = ['git'] + args
-    subp.check_call(args)
+set -eu -o pipefail
 
-def make_file_if_not_found(filename):
-    try:
-        with open(filename, 'x') as f:
-            pass
-    except FileExistsError as e:
-        pass
+: ${XDG_CONFIG_HOME:="$HOME/.config"}
 
-class Repo:
+declare -r ogit_top="$HOME"
+declare -r ogit_conf_d="$XDG_CONFIG_HOME/ogit"
+declare -r ogit_conf_file="$ogit_conf_d/config"
+declare -r ogit_repo_configs_d="$ogit_conf_d/configs"
 
-    @classmethod
-    def cmd(cls, cmd, repo_name, args):
-        conf = get_config()
-        repo = Repo.from_config(conf, repo_name)
-        repo.__getattribute__(cmd)(args)
-
-    @classmethod
-    def multi_cmd(cls, cmd, repo_names):
-        conf = get_config()
-        for repo in Repo.list_from_config(conf, repo_names):
-            if cmd != 'ls_files' and len(repo_names) > 1:
-                print("{0} {1}: {2}".format(prog_name, cmd, repo.name))
-            repo.__getattribute__(cmd)()
-
-    @classmethod
-    def from_config(cls, conf, name):
-        section = 'repo "{0}"'.format(name)
-        if not conf.has_section(section):
-            die("failed to find repo '{0}' in config file".format(name))
-
-        url = conf.get(section, 'url', fallback=None)
-        if url is None:
-            die('config file does not define repo."{0}".url'.format(name))
-
-        worktree = conf.get(section, 'worktree', fallback=None)
-        if worktree is None:
-            die('config file does not define repo."{0}".worktree'.format(name))
-        worktree = path.normpath(path.join(HOME, worktree))
-
-        repo = Repo()
-        repo.name = name
-        repo.url = url
-        repo.worktree = worktree
-        repo.git_dir_link = conf.getboolean(section, 'git_dir_link', fallback=(worktree != HOME))
-        repo.exclude = conf.get(section, 'exclude', fallback=None)
-        return repo
-
-    @classmethod
-    def list_from_config(cls, conf, names):
-        if len(names) == 0:
-            regex = re.compile('repo\s+"(.*)"')
-            for sect in conf.sections():
-                m = regex.match(sect)
-                if m is not None:
-                    names.append(m.groups()[0])
-
-        return [Repo.from_config(conf, name) for name in sorted(names)]
-
-    @property
-    def git_dir(self):
-        return path.join(OGIT_REPOS_DIR, self.name + '.git')
-
-    @property
-    def disjoint_git_dir(self):
-        return path.join(OGIT_CONFIG_HOME, 'repos-config', self.name + '.git')
-
-    def git_args(self, args):
-        args = ['git', '--git-dir', self.git_dir] + args
-        return args
-
-    def check_git(self, args):
-        subp.check_call(self.git_args(args))
-
-    def git(self, args):
-        subp.call(self.git_args(args))
-
-    def git_has_remote(self, remote):
-        for x in subp.check_output(self.git_args(['remote'])).decode().split('\n'):
-            if remote == x.strip():
-                return True
-        return False
-
-    def exec(self, args):
-        os.putenv('GIT_DIR', self.git_dir)
-        os.putenv('GIT_WORK_TREE', self.worktree)
-        os.execvp(args[0], args)
-
-    def shell(self, args):
-        shell = os.environ.get('SHELL', pwd.getpwuid(os.getuid()).pw_shell)
-        self.exec([shell])
-
-    def update_git_config(self):
-        self.check_git(['config', 'core.bare', 'false'])
-        self.check_git(['config', 'core.worktree', self.worktree])
-        self.check_git(['config', 'core.excludesfile', self.disjoint_exclude_file])
-        self.check_git(['config', 'remote.origin.url', self.url])
-        self.check_git(['config', 'remote.origin.fetch', '+refs/heads/*:refs/remotes/origin/*'])
-        self.check_git(['config', 'branch.master.remote', 'origin'])
-        self.check_git(['config', 'branch.master.merge', 'refs/heads/master'])
-
-    @property
-    def disjoint_info_dir(self):
-        return os.path.join(self.disjoint_git_dir, 'info')
-
-    @property
-    def disjoint_exclude_file(self):
-        return os.path.join(self.disjoint_info_dir, 'exclude')
-
-    @property
-    def disjoint_hooks_dir(self):
-        return os.path.join(self.disjoint_git_dir, 'hooks')
-
-    def init_disjoint_git_dir(self):
-        for d in [self.disjoint_git_dir, self.disjoint_info_dir, self.disjoint_hooks_dir]:
-            os.makedirs(d, exist_ok=True)
-            make_file_if_not_found(path.join(d, '.keep_me'))
-
-        make_file_if_not_found(self.disjoint_exclude_file)
-
-    def init_git_dir(self):
-        git_env = os.environ.copy()
-        git_env['GIT_TEMPLATE_DIR'] = ''
-        git_args = ['git', 'init']
-        if self.git_dir_link:
-            git_args += ['--separate-git-dir', self.git_dir, self.worktree]
-        elif not path.exists(self.git_dir):
-            git_args += ['--bare', self.git_dir]
-        subp.check_call(git_args, env=git_env)
-        subp.check_call(['ln', '-sfT', self.disjoint_hooks_dir, path.join(self.git_dir, 'hooks')])
-
-    def init(self):
-        self.init_disjoint_git_dir()
-        self.init_git_dir()
-        self.update_git_config()
-
-    def is_dirty(self):
-        return self.git(['diff', '--quiet', '--no-ext-diff']) != 0 \
-            or self.git(['diff', '--quiet', '--no-ext-diff', '--cached']) != 0
-
-    def fetch(self):
-        self.git(['fetch', '--all'])
-
-    def status(self):
-        if self.is_dirty():
-            self.git(['status', '--short'])
-
-    def pull(self):
-        self.git(['pull'])
-
-    def ls_files(self):
-        with subp.Popen(self.git_args(['ls-files']), stdout=subp.PIPE) as proc:
-            for line in proc.stdout:
-                sys.stdout.write(path.join(self.worktree, line.decode()))
-
-    def config(self, args):
-        self.check_git(['config'] + args)
-
-def get_config():
-    conf = configparser.ConfigParser(allow_no_value=True)
-    conf.read(OGIT_CONFIG_MAIN)
-    for inc in conf.options('include'):
-        for g in glob.iglob(path.join(OGIT_CONFIG_HOME, inc)):
-            conf.read(g)
-    return conf
-
-def cmd_help(args):
-    print('usage: {0} <command> [args]'.format(prog_name))
-    print()
-    print('Commands:')
-    for cmd in cmd_table.keys():
-        print('  {0}'.format(cmd))
-
-def cmd_list(args):
-    if len(args) != 0:
-        die("usage error")
-
-    conf = get_config()
-    for repo in Repo.list_from_config(conf, []):
-        print("{0}:{1}{2}".format(repo.name, ' ' * (36 - len(repo.name)), repo.worktree))
-
-def cmd_init(args):
-    Repo.multi_cmd('init', args)
-
-def cmd_fetch(args):
-    Repo.multi_cmd('fetch', args)
-
-def cmd_status(args):
-    Repo.multi_cmd('status', args)
-
-def cmd_pull(args):
-    Repo.multi_cmd('pull', args)
-
-def cmd_exec(args):
-    if len(args) < 2:
-        die('usage error')
-    repo_name = args.pop(0)
-    Repo.cmd('exec', repo_name, args)
-
-def cmd_shell(args):
-    if len(args) != 1:
-        die('usage error')
-    repo_name = args.pop(0)
-    Repo.cmd('shell', repo_name, args)
-
-def cmd_config(args):
-    if len(args) < 1:
-        die('usage error')
-    repo_name = args.pop(0)
-    Repo.cmd('config', repo_name, args)
-
-def cmd_ls_files(args):
-    Repo.multi_cmd('ls_files', args)
-
-cmd_table = {
-    'help': cmd_help,
-    'list': cmd_list,
-    'init': cmd_init,
-    'fetch': cmd_fetch,
-    'status': cmd_status,
-    'pull': cmd_pull,
-    'exec': cmd_exec,
-    'shell': cmd_shell,
-    'ls-files': cmd_ls_files,
-    'config': cmd_config,
+function ogit_die {
+    echo >&2 "ogit ${ogit_cmd_name:-}: error: $@"
+    exit 1
 }
 
-def main(args):
-    global prog_name
+function ogit_info {
+    echo "ogit ${ogit_cmd_name:-}: $@"
+}
 
-    prog_name = path.basename(args.pop(0))
+function ogit_usage_error {
+    echo >&2 "ogit ${ogit_cmd_name:-}: usage error: $@"
+    exit 1
+}
 
-    if len(args) == 0:
-        cmd_name = 'help'
-    else:
-        cmd_name = args.pop(0)
+function ogit_is_cmd {
+    ogit_list_cmds | grep -q -e "^$1\$"
+}
 
-    cmd_func = cmd_table.get(cmd_name, None)
-    if cmd_func is None:
-        die("unknown command '{0}'".format(cmd_name))
+function ogit_list_cmds {
+    declare -Ff | awk 'match($3, /^ogit_cmd_(.*)/, m)  { print m[1] }' | sort
+}
 
-    cmd_func(args)
+function ogit_list_repos {
+    ls "$ogit_repo_configs_d"/*/config | sed -e 's%^.*/\([^/]*\)/config$%\1%'
+}
 
-if __name__ == '__main__':
-    main(sys.argv)
+function ogit_check_repo_name_list {
+    declare repo_name
+
+    for repo_name in "${repo_name_list[@]}"; do
+        ogit_check_repo_name
+    done
+
+    return 0
+}
+
+function ogit_check_repo_name {
+    if ! repo_name_is_valid; then
+        ogit_die "repo name is invalid: '$repo_name'"
+    fi
+}
+
+function ogit_mux_repo_cmd {
+    declare repo_name_list=("$@")
+    declare repo_name
+
+    if [[ "${#repo_name_list[@]}" -eq 0 ]]; then
+        for repo_name in $(ogit_list_repos); do
+            repo_name_list+=("$repo_name")
+        done
+    fi
+
+    ogit_check_repo_name_list
+
+    for repo_name in "${repo_name_list[@]}"; do
+        if [[ "$repo_cmd_name" != "ls-files" ]]; then
+            ogit_info "$repo_name"
+        fi
+        repo_cmd_${repo_cmd_name}
+    done
+}
+
+function repo_exists {
+    ogit_list_repos | grep -q -e "^${repo_name}$"
+}
+
+function repo_name_is_valid {
+    [[ "$repo_name" != */* ]] && [[ "$repo_name" != -* ]]
+}
+
+function repo_git_d {
+    echo "$ogit_conf_d/git-dirs/${repo_name}.git"
+}
+
+function repo_conf_d {
+    echo "$ogit_conf_d/configs/$repo_name"
+}
+
+function repo_hooks_d {
+    echo "$(repo_conf_d)/hooks"
+}
+
+function repo_ogit_conf_file {
+    echo "$(repo_conf_d)/config"
+}
+
+function repo_env {
+    GIT_TEMPLATE_DIR= \
+    GIT_DIR="$(repo_git_d)" \
+    "$@"
+}
+function repo_git {
+    repo_env git "$@"
+}
+
+function repo_ogit_conf_get {
+    git config --file "$(repo_ogit_conf_file)" --get "$@" \
+    | awk "{ gsub(/\\\${ogit_top}/, \"$ogit_top\"); print \$0 }"
+}
+
+function repo_worktree {
+    repo_ogit_conf_get ogit-repo.worktree
+}
+
+function repo_ogit_url {
+    repo_ogit_conf_get ogit-repo.url
+}
+
+function repo_has_git_dir_link {
+    [[ "$(repo_ogit_conf_get --bool ogit-repo.git-dir-link)" != "false" ]]
+}
+
+function repo_update_git_config {
+    repo_git config core.bare false
+    repo_git config core.worktree "$(repo_worktree)"
+    repo_git config core.excludesfile "$(repo_conf_d)/exclude"
+    repo_git config remote.origin.url "$(repo_ogit_url)"
+    repo_git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+    repo_git config branch.master.remote origin
+    repo_git config branch.master.merge refs/heads/master
+    repo_git config include.path "$ogit_conf_file"
+    repo_git config include.path "$(repo_ogit_conf_file)"
+    ln -sfT "$(repo_hooks_d)" "$(repo_git_d)/hooks"
+}
+
+function repo_is_git_initialized {
+    if repo_git rev-parse --git-dir >&/dev/null; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+function repo_init {
+    declare -a git_args=
+
+    git_args=('git' 'init' '--quiet')
+    if repo_has_git_dir_link; then
+        git_args+=('--separate-git-dir' "$(repo_git_d)" "$(repo_worktree)")
+    else 
+        if ! [[ -d "$(repo_git_d)" ]]; then
+            git_args+=('--bare' "$(repo_git_d)")
+        else
+            git_args+=("$(repo_git_d)")
+        fi
+    fi
+
+    mkdir -p "$(dirname "$(repo_git_d)")"
+    mkdir -p "$(dirname "$(repo_worktree)")"
+    # FIXME: This rm opens a race condition.
+    rm -f "$(repo_worktree)/.git"
+    GIT_TEMPLATE_DIR= "${git_args[@]}"
+    repo_update_git_config
+}
+
+function repo_is_clean {
+    repo_git diff --quiet --no-ext-diff \
+    && repo_git diff --quiet --no-ext-diff
+}
+
+function repo_cmd_sync {
+    declare is_reinit=
+
+    if repo_is_git_initialized; then
+        is_reinit='true'
+    else
+        is_reinit='false'
+    fi
+
+    repo_init
+    if [[ "$is_reinit" = 'true' ]]; then
+        repo_git pull
+    else
+        repo_git fetch origin
+        repo_git reset --quiet origin/master
+        repo_git merge origin/master
+    fi
+}
+
+function repo_cmd_status {
+    repo_git status --short
+}
+
+function repo_cmd_ls-files {
+    repo_git ls-files | awk "{ print \"$(repo_worktree)/\" \$0 }" | sort
+}
+
+function repo_cmd_pull {
+    repo_git pull "$@"
+}
+
+function repo_cmd_merge {
+    repo_git merge "$@"
+}
+
+function repo_cmd_push {
+    repo_git push "$@"
+}
+
+function repo_cmd_exec {
+    repo_env exec "$@"
+}
+
+function repo_cmd_shell {
+    repo_env exec "$SHELL" "$@"
+}
+
+function ogit_cmd_help {
+    declare cmd=
+
+    echo "usage: ogit <command> [args]"
+    echo
+    echo "Available commands are:"
+    ogit_list_cmds | awk '{ print "  " $0 }'
+}
+
+function ogit_cmd_list {
+    declare repo_name
+
+    if [[ $# -ne 0 ]]; then
+        ogit_usage_error "too many args"
+    fi
+    
+    for repo_name in $(ogit_list_repos); do
+        printf "%s %s\n" "${repo_name}" "$(repo_worktree)"
+    done | column -t
+}
+
+function ogit_cmd_status {
+    declare -r repo_cmd_name='status'
+    ogit_mux_repo_cmd "$@"
+}
+
+function ogit_cmd_ls-files {
+    declare -r repo_cmd_name='ls-files'
+    ogit_mux_repo_cmd "$@"
+}
+
+function ogit_cmd_exec {
+    if [[ $# -lt 1 ]]; then
+        ogit_usage_error "missing repo argument"
+    fi
+
+    declare -r repo_name="$1"
+    shift
+
+    ogit_check_repo_name
+    repo_cmd_exec "$@"
+}
+
+function ogit_cmd_shell {
+    if [[ $# -lt 1 ]]; then
+        ogit_usage_error "missing repo argument"
+    fi
+
+    declare -r repo_name="$1"
+    shift
+
+    ogit_check_repo_name
+    repo_cmd_shell "$@"
+}
+
+function ogit_cmd_sync {
+    declare -r repo_cmd_name='sync'
+    ogit_mux_repo_cmd "$@"
+}
+
+function main {
+    declare cmd
+
+    if [[ $# = 0 ]]; then
+        cmd='help'
+    else
+        case "$1" in
+            -h|--help)
+                cmd='help'
+                shift
+                ;;
+            -*)
+                ogit_usage_error "unknown option '$1'"
+                ;;
+            *)
+                cmd="$1"
+                shift
+                ;;
+        esac
+    fi
+
+    if ! ogit_is_cmd "$cmd"; then
+        ogit_usage_error "unknown command '$cmd'"
+    fi
+
+    declare -r ogit_cmd_name="$cmd"
+    ogit_cmd_${cmd} "$@"
+}
+
+main "$@"
